- hosts: webserver1
  tasks:
          - name: deploy nginx docker container
            docker_container:
                    image: joachimopdenakker/systeembeheernginx1
                    name: nginx
                    state: started
                    auto_remove: true
                    ports:
                            - "8081:80"
- hosts: webserver2
  tasks:
          - name: deploy nginx docker container
            docker_container:
                    image: joachimopdenakker/systeembeheernginx2
                    name: nginx
                    state: started
                    auto_remove: true
                    ports:
                            - "8082:80"
- hosts: loadbalancer
  tasks:
          - name: deploy haproxy docker container
            docker_container:
                    image: joachimopdenakker/systeembeheerhaproxy
                    name: haproxy
                    state: started
                    autoremove: true
                    ports:
                            - "8080:80"
                            - "8404:8404"
